# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lz/kejk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lz/kejk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lz/kejk/CMakeFiles /home/lz/kejk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lz/kejk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named app_autogen

# Build rule for target.
app_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_autogen
.PHONY : app_autogen

# fast build rule for target.
app_autogen/fast:
	$(MAKE) -f CMakeFiles/app_autogen.dir/build.make CMakeFiles/app_autogen.dir/build
.PHONY : app_autogen/fast

OpenGlVideoQtQuick.o: OpenGlVideoQtQuick.cpp.o

.PHONY : OpenGlVideoQtQuick.o

# target to build an object file
OpenGlVideoQtQuick.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/OpenGlVideoQtQuick.cpp.o
.PHONY : OpenGlVideoQtQuick.cpp.o

OpenGlVideoQtQuick.i: OpenGlVideoQtQuick.cpp.i

.PHONY : OpenGlVideoQtQuick.i

# target to preprocess a source file
OpenGlVideoQtQuick.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/OpenGlVideoQtQuick.cpp.i
.PHONY : OpenGlVideoQtQuick.cpp.i

OpenGlVideoQtQuick.s: OpenGlVideoQtQuick.cpp.s

.PHONY : OpenGlVideoQtQuick.s

# target to generate assembly for a file
OpenGlVideoQtQuick.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/OpenGlVideoQtQuick.cpp.s
.PHONY : OpenGlVideoQtQuick.cpp.s

app_autogen/mocs_compilation.o: app_autogen/mocs_compilation.cpp.o

.PHONY : app_autogen/mocs_compilation.o

# target to build an object file
app_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app_autogen/mocs_compilation.cpp.o
.PHONY : app_autogen/mocs_compilation.cpp.o

app_autogen/mocs_compilation.i: app_autogen/mocs_compilation.cpp.i

.PHONY : app_autogen/mocs_compilation.i

# target to preprocess a source file
app_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app_autogen/mocs_compilation.cpp.i
.PHONY : app_autogen/mocs_compilation.cpp.i

app_autogen/mocs_compilation.s: app_autogen/mocs_compilation.cpp.s

.PHONY : app_autogen/mocs_compilation.s

# target to generate assembly for a file
app_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app_autogen/mocs_compilation.cpp.s
.PHONY : app_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.s
.PHONY : main.cpp.s

qrc_qml.o: qrc_qml.cpp.o

.PHONY : qrc_qml.o

# target to build an object file
qrc_qml.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/qrc_qml.cpp.o
.PHONY : qrc_qml.cpp.o

qrc_qml.i: qrc_qml.cpp.i

.PHONY : qrc_qml.i

# target to preprocess a source file
qrc_qml.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/qrc_qml.cpp.i
.PHONY : qrc_qml.cpp.i

qrc_qml.s: qrc_qml.cpp.s

.PHONY : qrc_qml.s

# target to generate assembly for a file
qrc_qml.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/qrc_qml.cpp.s
.PHONY : qrc_qml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... app"
	@echo "... edit_cache"
	@echo "... app_autogen"
	@echo "... OpenGlVideoQtQuick.o"
	@echo "... OpenGlVideoQtQuick.i"
	@echo "... OpenGlVideoQtQuick.s"
	@echo "... app_autogen/mocs_compilation.o"
	@echo "... app_autogen/mocs_compilation.i"
	@echo "... app_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qrc_qml.o"
	@echo "... qrc_qml.i"
	@echo "... qrc_qml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

